version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: gamematchai_postgres
    restart: always

    environment:
      POSTGRES_DB: gamematch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: negs@2704

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/gamematchai.sql:/docker-entrypoint-initdb.d/01-gamematchai.sql:ro

    networks:
      - gamematchai_network


  backend:
    build:
      context: ./backend

    container_name: gamematchai_backend
    restart: always

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: gamematch
      DB_USER: postgres
      DB_PASSWORD: negs@2704
      RAWG_API_KEY: 2212120717754e13b480a7bb4734e927

    ports:
      - "8000:8000"

    networks:
      - gamematchai_network


  frontend:
    build:
      context: ./frontend

    container_name: gamematchai_frontend
    restart: always

    depends_on:
      - backend

    ports:
      - "5173:5173"

    networks:
      - gamematchai_network


volumes:
  postgres_data:


networks:
  gamematchai_network:
    driver: bridge